language: php

php:
  - "5.5"

mysql:
  database: db_test
  username: root
  encoding: utf8

before_script:
  - npm install -g grunt-cli
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - "java -jar selenium-server-standalone-2.43.1.jar > /tmp/selenium-log 2> /tmp/selenium.error &"
  - composer install
  - mysql -e 'create database db_test'
  - mysql -u root db_test < script-ddl.sql
  - php -S localhost:8000 -t public/ &

script:
  - grunt travis --verbose
  - phpunit
